#!/usr/bin/env python3
"""Gzip webui/index.html into firmware/src/webui_gz.h.

Usage: python webui/build.py
Stdlib only. The output header is generated — do not edit it by hand.
"""

import gzip
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "webui" / "index.html"
OUT = ROOT / "firmware" / "src" / "webui_gz.h"

# Keep the byte array to roughly this many lines (many bytes per line is fine).
MAX_ARRAY_LINES = 8


def main() -> int:
    html = SRC.read_bytes()
    # mtime=0 for deterministic output (no spurious diffs on rebuild).
    gz = gzip.compress(html, compresslevel=9, mtime=0)

    per_line = max(1, math.ceil(len(gz) / MAX_ARRAY_LINES))
    lines = []
    for i in range(0, len(gz), per_line):
        chunk = gz[i : i + per_line]
        lines.append("  " + ",".join("0x%02x" % b for b in chunk) + ",")

    header = "\n".join(
        [
            "// Generated by webui/build.py from webui/index.html - DO NOT EDIT.",
            "// Rebuild with: python webui/build.py",
            "#ifndef VIA_LUCIS_WEBUI_GZ_H",
            "#define VIA_LUCIS_WEBUI_GZ_H",
            "",
            "#include <stddef.h>",
            "#include <stdint.h>",
            "",
            "#ifndef PROGMEM",
            "#define PROGMEM",
            "#endif",
            "",
            "const uint8_t kWebUiGz[] PROGMEM = {",
            *lines,
            "};",
            "const size_t kWebUiGzLen = %d;" % len(gz),
            "",
            "#endif  // VIA_LUCIS_WEBUI_GZ_H",
            "",
        ]
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header, encoding="ascii", newline="\n")
    print(
        "webui_gz.h: %d bytes html -> %d bytes gzip -> %s"
        % (len(html), len(gz), OUT.relative_to(ROOT))
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
